name: Brim release

on:
  push:
    tags:
      - v*brim*

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - run: ./brim/release
      - uses: svenstaro/upload-release-action@1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zeek-*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
